---
- name: Коммит и пуш изменений в Git репозиторий
  hosts: localhost
  gather_facts: true  # Включаем сбор фактов

  vars:
    file_path: "/Users/andreyshabunov/PhpstormProjects/hexlet/Ansible/modules/gitlab/commit_file.md"
    repo_path: "/Users/andreyshabunov/PhpstormProjects/hexlet/Ansible"
    number_of_commits: 100

  tasks:
    - name: Выполнение 100 коммитов и пушей
      include_tasks: commit_tasks.yml
